const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.FileSystem,
		C3.Plugins.Dictionary,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.PlatformInfo.Cnds.IsWebExport,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.PlatformInfo.Cnds.IsWindowsWebView2Export,
		C3.Plugins.FileSystem.Acts.WriteTextFile,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.FileSystem.Acts.Delete,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.FileSystem.Acts.ReadTextFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.FileSystem.Cnds.OnFileOperationError,
		C3.Plugins.FileSystem.Cnds.OnFileOperationComplete,
		C3.Plugins.FileSystem.Exps.FileText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.zeropad
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Browser: 0},
	{Mouse: 0},
	{dimming: 0},
	{hourHandle: 0},
	{gear: 0},
	{minuteHandle: 0},
	{secondHandle: 0},
	{testSprite: 0},
	{MoveTo: 0},
	{minColor: 0},
	{minOutlines: 0},
	{minInLines: 0},
	{HourText: 0},
	{MinText: 0},
	{SecText: 0},
	{ClickPowerText: 0},
	{topic: 0},
	{hOrig: 0},
	{wOrig: 0},
	{available: 0},
	{upgradeButton: 0},
	{cPowerPriceText: 0},
	{autoSecPriceText: 0},
	{autoSecText: 0},
	{hourMarker: 0},
	{minSpeedPriceText: 0},
	{autoMinPriceText: 0},
	{autoMinText: 0},
	{checkBox: 0},
	{minIdleCheck: 0},
	{upgTitleText: 0},
	{priceKeeperText: 0},
	{inflationText: 0},
	{prestigePriceText: 0},
	{PrestigeText: 0},
	{autoSecBuyerPrice: 0},
	{autoMinBuyerPrice: 0},
	{Bullet: 0},
	{Fade: 0},
	{Tween: 0},
	{hParticle: 0},
	{hHover: 0},
	{minMultiPriceText: 0},
	{bigParticle: 0},
	{upText: 0},
	{debugText: 0},
	{sentWaves: 0},
	{hourEffect: 0},
	{hourEffectLeft: 0},
	{hourEffectRight: 0},
	{cursor: 0},
	{smallParticle: 0},
	{MinMultiplier: 0},
	{midParticle: 0},
	{MinSpeedText: 0},
	{achievementsTitle: 0},
	{victoryText: 0},
	{Audio: 0},
	{sfxToggler: 0},
	{hourValue: 0},
	{bought: 0},
	{hUnlock: 0},
	{hour: 0},
	{boughtText: 0},
	{availableText: 0},
	{unlockText: 0},
	{gearPointer: 0},
	{hCostText: 0},
	{firstSeenText: 0},
	{instruction1: 0},
	{instruction2: 0},
	{instruction3: 0},
	{instruction4: 0},
	{instruction5: 0},
	{infoText: 0},
	{infoPanel: 0},
	{Sprite: 0},
	{clicked: 0},
	{questionMark: 0},
	{secButtonCheat: 0},
	{minButtonCheat: 0},
	{Touch: 0},
	{wishListText: 0},
	{url: 0},
	{wishListButton: 0},
	{timePlayed: 0},
	{timerText: 0},
	{clickCount: 0},
	{clickCountText: 0},
	{creditsText: 0},
	{wtfButton: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{FileSystem: 0},
	{DictionaryStats: 0},
	{playButton: 0},
	{resetButton: 0},
	{type: 0},
	{statsText: 0},
	{buttonText: 0},
	{deleteStatsButton: 0},
	{DictionaryGameData: 0},
	{secSFXtoggler: 0},
	{UpgradeText: 0},
	{minMultiplier: 0},
	{particleSpeed: 0},
	{particlesInPlace: 0},
	{particleAmount: 0},
	{days: 0},
	{minIdleOn: 0},
	{minIdleRiseSpeed: 0},
	{minRiseSpeed: 0},
	{origMinRiseSpeed: 0},
	{hours: 0},
	{minutes: 0},
	{clickPower: 0},
	{seconds: 0},
	{amount: 0},
	{autoAutoCost: 0},
	{autoHourCost: 0},
	{hourSpeedCost: 0},
	{prestigeCost: 0},
	{prestige: 0},
	{inflationOn: 0},
	{priceKeepCost: 0},
	{dimmingSpeed: 0},
	{autoMinCost: 0},
	{autoSecCost: 0},
	{cPowerCost: 0},
	{minSpeedCost: 0},
	{curInflation: 0},
	{curPrestige: 0},
	{autoBuyers: 0},
	{autoHours: 0},
	{autoMins: 0},
	{autoSecs: 0},
	{uid: 0},
	{toggle: 0},
	{minMultiCost: 0},
	{maxMinSpeed: 0},
	{maxMinMultiplier: 0},
	{maxAutoSecs: 0},
	{maxClickPower: 0},
	{gameStarted: 0},
	{dimMinimum: 0},
	{s: 0},
	{m: 0},
	{h: 0},
	{autoSecVolume: 0},
	{minAutoSecPlaybackRate: 0},
	{maxAutoSecPlaybackRate: 0},
	{secSFXon: 0},
	{jamClickPower: 0},
	{autoMin: 0},
	{hDimmingSpeed: 0},
	{autoHour: 0},
	{hourCost: 0},
	{hEffectOn: 0},
	{allMultiplier: 0},
	{wonTheGame: 0},
	{hUnlockValue: 0},
	{lowestClickCount: 0},
	{lowestClickCountTime: 0},
	{highestClickCount: 0},
	{highestClickCountTime: 0},
	{shortestTime: 0},
	{shortestTimeClickCount: 0},
	{longestTime: 0},
	{longestTimeClickCount: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	hourHandle: class extends self.ISpriteInstance {},
	gear: class extends self.ISpriteInstance {},
	minuteHandle: class extends self.ISpriteInstance {},
	secondHandle: class extends self.ISpriteInstance {},
	testSprite: class extends self.ISpriteInstance {},
	minColor: class extends self.ISpriteInstance {},
	minOutlines: class extends self.ISpriteInstance {},
	minInLines: class extends self.ISpriteInstance {},
	HourText: class extends self.ITextInstance {},
	MinText: class extends self.ITextInstance {},
	SecText: class extends self.ITextInstance {},
	ClickPowerText: class extends self.ITextInstance {},
	upgradeButton: class extends self.ISpriteInstance {},
	cPowerPriceText: class extends self.ITextInstance {},
	autoSecPriceText: class extends self.ITextInstance {},
	autoSecText: class extends self.ITextInstance {},
	hourMarker: class extends self.ISpriteInstance {},
	minSpeedPriceText: class extends self.ITextInstance {},
	autoMinPriceText: class extends self.ITextInstance {},
	autoMinText: class extends self.ITextInstance {},
	checkBox: class extends self.ISpriteInstance {},
	minIdleCheck: class extends self.ITextInstance {},
	upgTitleText: class extends self.ITextInstance {},
	priceKeeperText: class extends self.ITextInstance {},
	inflationText: class extends self.ITextInstance {},
	prestigePriceText: class extends self.ITextInstance {},
	PrestigeText: class extends self.ITextInstance {},
	autoSecBuyerPrice: class extends self.ITextInstance {},
	autoMinBuyerPrice: class extends self.ITextInstance {},
	hParticle: class extends self.ISpriteInstance {},
	hHover: class extends self.ISpriteInstance {},
	minMultiPriceText: class extends self.ITextInstance {},
	bigParticle: class extends self.IParticlesInstance {},
	upText: class extends self.ITextInstance {},
	debugText: class extends self.ITextInstance {},
	hourEffect: class extends self.ISpriteInstance {},
	hourEffectLeft: class extends self.ISpriteInstance {},
	hourEffectRight: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	smallParticle: class extends self.IParticlesInstance {},
	MinMultiplier: class extends self.ITextInstance {},
	midParticle: class extends self.IParticlesInstance {},
	MinSpeedText: class extends self.ITextInstance {},
	achievementsTitle: class extends self.ITextInstance {},
	victoryText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	sfxToggler: class extends self.ISpriteInstance {},
	hUnlock: class extends self.ISpriteInstance {},
	unlockText: class extends self.ITextInstance {},
	gearPointer: class extends self.ISpriteInstance {},
	hCostText: class extends self.ITextInstance {},
	infoText: class extends self.ITextInstance {},
	infoPanel: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	questionMark: class extends self.ISpriteInstance {},
	secButtonCheat: class extends self.ISpriteInstance {},
	minButtonCheat: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	wishListText: class extends self.ITextInstance {},
	wishListButton: class extends self.ISpriteInstance {},
	timerText: class extends self.ITextInstance {},
	clickCountText: class extends self.ITextInstance {},
	creditsText: class extends self.ITextInstance {},
	wtfButton: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	DictionaryStats: class extends self.IDictionaryInstance {},
	playButton: class extends self.ISpriteInstance {},
	resetButton: class extends self.ISpriteInstance {},
	statsText: class extends self.ITextInstance {},
	buttonText: class extends self.ITextInstance {},
	deleteStatsButton: class extends self.ISpriteInstance {},
	DictionaryGameData: class extends self.IDictionaryInstance {},
	secSFXtoggler: class extends self.ISpriteInstance {},
	UpgradeText: class extends self.ITextInstance {}
}